
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NCC
 */
public class Adminpanel extends javax.swing.JFrame {

    /**
     * Creates new form pr
     */
    public Adminpanel() {
        initComponents();
        setIcon();
           setColor(Homemenu);
        resetColor(Productmenu);
        resetColor(IcecreamMenu);
        resetColor(Ordermenu);
        resetColor(Customermenu);
        resetColor(Feedbackmenu);
        Homepage.setVisible(true);
        AddPoduct.setVisible(false);
        Order.setVisible(false);
        CustomerInfo.setVisible(false);
        feedbackinfo.setVisible(false);
        IcecreamInfo.setVisible(false);
             setDefaultCloseOperation(Adminpanel.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        AddPoduct = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pitem_no = new javax.swing.JTextField();
        prod_name = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        pqty = new javax.swing.JTextField();
        p1price = new javax.swing.JTextField();
        ptotal = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        Order = new javax.swing.JPanel();
        dltorder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        order = new javax.swing.JTable();
        CustomerInfo = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        customer = new javax.swing.JTable();
        feedbackinfo = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        feedback = new javax.swing.JTable();
        IcecreamInfo = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        viewproduct = new javax.swing.JTable();
        Homepage = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        Productmenu = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        IcecreamMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Ordermenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Customermenu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Feedbackmenu = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        Homemenu = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(961, 580));
        setResizable(false);

        AddPoduct.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Product ID");

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Product Name");

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date & Time");

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Quantity");

        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("One Item Price");

        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total Price");

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ADD NEW PRODUCT");

        pqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pqtyKeyReleased(evt);
            }
        });

        p1price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                p1priceKeyReleased(evt);
            }
        });

        delete.setBackground(new java.awt.Color(204, 0, 0));
        delete.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 15)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        add.setBackground(new java.awt.Color(102, 204, 0));
        add.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 15)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(0, 204, 204));
        update.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 15)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddPoductLayout = new javax.swing.GroupLayout(AddPoduct);
        AddPoduct.setLayout(AddPoductLayout);
        AddPoductLayout.setHorizontalGroup(
            AddPoductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPoductLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(AddPoductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddPoductLayout.createSequentialGroup()
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(AddPoductLayout.createSequentialGroup()
                        .addGroup(AddPoductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AddPoductLayout.createSequentialGroup()
                                .addGroup(AddPoductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(101, 101, 101)
                                .addGroup(AddPoductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pitem_no, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(prod_name, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(pqty, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(p1price, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(ptotal, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(jDateChooser3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(158, 158, 158)
                                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(218, Short.MAX_VALUE))))
        );
        AddPoductLayout.setVerticalGroup(
            AddPoductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPoductLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AddPoductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pitem_no, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddPoductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prod_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(AddPoductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AddPoductLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(AddPoductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pqty, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(AddPoductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p1price, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(AddPoductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ptotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(AddPoductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        Order.setBackground(new java.awt.Color(0, 0, 0));

        dltorder.setBackground(new java.awt.Color(204, 0, 0));
        dltorder.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 15)); // NOI18N
        dltorder.setForeground(new java.awt.Color(255, 255, 255));
        dltorder.setText("DELETE ORDER");
        dltorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltorderActionPerformed(evt);
            }
        });

        order.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "Product ID", "Quantity", "Phone no", "Date", "Address", "Order No"
            }
        ));
        order.setEnabled(false);
        jScrollPane1.setViewportView(order);

        javax.swing.GroupLayout OrderLayout = new javax.swing.GroupLayout(Order);
        Order.setLayout(OrderLayout);
        OrderLayout.setHorizontalGroup(
            OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrderLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dltorder, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        OrderLayout.setVerticalGroup(
            OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderLayout.createSequentialGroup()
                .addComponent(dltorder, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        CustomerInfo.setBackground(new java.awt.Color(0, 0, 0));

        customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "Customer Name", "Password", "Date", "Phn no", "Address"
            }
        ));
        customer.setEnabled(false);
        jScrollPane2.setViewportView(customer);

        javax.swing.GroupLayout CustomerInfoLayout = new javax.swing.GroupLayout(CustomerInfo);
        CustomerInfo.setLayout(CustomerInfoLayout);
        CustomerInfoLayout.setHorizontalGroup(
            CustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
        );
        CustomerInfoLayout.setVerticalGroup(
            CustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE))
        );

        feedbackinfo.setBackground(new java.awt.Color(0, 0, 0));
        feedbackinfo.setPreferredSize(new java.awt.Dimension(876, 583));

        feedback.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Customer ID", "Date", "Feedback"
            }
        ));
        feedback.setEnabled(false);
        jScrollPane4.setViewportView(feedback);

        javax.swing.GroupLayout feedbackinfoLayout = new javax.swing.GroupLayout(feedbackinfo);
        feedbackinfo.setLayout(feedbackinfoLayout);
        feedbackinfoLayout.setHorizontalGroup(
            feedbackinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
        );
        feedbackinfoLayout.setVerticalGroup(
            feedbackinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        IcecreamInfo.setBackground(new java.awt.Color(0, 0, 0));
        IcecreamInfo.setPreferredSize(new java.awt.Dimension(876, 583));

        viewproduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Quantity", "PerPrice"
            }
        ));
        viewproduct.setEnabled(false);
        jScrollPane5.setViewportView(viewproduct);

        javax.swing.GroupLayout IcecreamInfoLayout = new javax.swing.GroupLayout(IcecreamInfo);
        IcecreamInfo.setLayout(IcecreamInfoLayout);
        IcecreamInfoLayout.setHorizontalGroup(
            IcecreamInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
        );
        IcecreamInfoLayout.setVerticalGroup(
            IcecreamInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        Homepage.setBackground(new java.awt.Color(0, 0, 0));
        Homepage.setPreferredSize(new java.awt.Dimension(876, 583));
        Homepage.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Monotype Corsiva", 2, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("WELCOME   TO  ICECREAM  PARLOUR");
        Homepage.add(jLabel17);
        jLabel17.setBounds(60, 200, 460, 80);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black-diamond-bg.jpg"))); // NOI18N
        jLabel18.setText("jLabel18");
        Homepage.add(jLabel18);
        jLabel18.setBounds(0, 0, 960, 540);

        jLayeredPane1.setLayer(AddPoduct, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Order, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(CustomerInfo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(feedbackinfo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(IcecreamInfo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Homepage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddPoduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Order, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CustomerInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(feedbackinfo, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(IcecreamInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Homepage, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddPoduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Order, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CustomerInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(feedbackinfo, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(IcecreamInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Homepage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(51, 51, 51));

        Productmenu.setBackground(new java.awt.Color(51, 51, 51));
        Productmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel11.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PRODUCT");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ProductmenuLayout = new javax.swing.GroupLayout(Productmenu);
        Productmenu.setLayout(ProductmenuLayout);
        ProductmenuLayout.setHorizontalGroup(
            ProductmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductmenuLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        ProductmenuLayout.setVerticalGroup(
            ProductmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        IcecreamMenu.setBackground(new java.awt.Color(51, 51, 51));
        IcecreamMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" ICECREAM");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout IcecreamMenuLayout = new javax.swing.GroupLayout(IcecreamMenu);
        IcecreamMenu.setLayout(IcecreamMenuLayout);
        IcecreamMenuLayout.setHorizontalGroup(
            IcecreamMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IcecreamMenuLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        IcecreamMenuLayout.setVerticalGroup(
            IcecreamMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IcecreamMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Ordermenu.setBackground(new java.awt.Color(51, 51, 51));
        Ordermenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  ORDER");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout OrdermenuLayout = new javax.swing.GroupLayout(Ordermenu);
        Ordermenu.setLayout(OrdermenuLayout);
        OrdermenuLayout.setHorizontalGroup(
            OrdermenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrdermenuLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        OrdermenuLayout.setVerticalGroup(
            OrdermenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrdermenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Customermenu.setBackground(new java.awt.Color(51, 51, 51));
        Customermenu.setForeground(new java.awt.Color(255, 255, 255));
        Customermenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CUSTOMER");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CustomermenuLayout = new javax.swing.GroupLayout(Customermenu);
        Customermenu.setLayout(CustomermenuLayout);
        CustomermenuLayout.setHorizontalGroup(
            CustomermenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomermenuLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(17, 17, 17))
        );
        CustomermenuLayout.setVerticalGroup(
            CustomermenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomermenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Feedbackmenu.setBackground(new java.awt.Color(51, 51, 51));
        Feedbackmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel12.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("FEEDBACK");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout FeedbackmenuLayout = new javax.swing.GroupLayout(Feedbackmenu);
        Feedbackmenu.setLayout(FeedbackmenuLayout);
        FeedbackmenuLayout.setHorizontalGroup(
            FeedbackmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FeedbackmenuLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(31, 31, 31))
        );
        FeedbackmenuLayout.setVerticalGroup(
            FeedbackmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeedbackmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        logout.setBackground(new java.awt.Color(51, 51, 51));
        logout.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("LOGOUT");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        Homemenu.setBackground(new java.awt.Color(51, 51, 51));
        Homemenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel16.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("   HOME ");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HomemenuLayout = new javax.swing.GroupLayout(Homemenu);
        Homemenu.setLayout(HomemenuLayout);
        HomemenuLayout.setHorizontalGroup(
            HomemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomemenuLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(33, 33, 33))
        );
        HomemenuLayout.setVerticalGroup(
            HomemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomemenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(Homemenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Productmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IcecreamMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Ordermenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Customermenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Feedbackmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Productmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(IcecreamMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Ordermenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Customermenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Feedbackmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Homemenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dltorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltorderActionPerformed
        // TODO add your handling code here:
          DltOrder dr= new DltOrder();
        dr.setVisible(true);
    }//GEN-LAST:event_dltorderActionPerformed

    private void pqtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pqtyKeyReleased
        // TODO add your handling code here:
           Pattern pa=Pattern.compile("[0-9]+");
                Matcher ma= pa.matcher(pqty.getText());
                if(!ma.matches())
                {
                    JOptionPane.showMessageDialog(null,"Please fill the valid value in quantity"); 
                    pqty.setText("");
                }
        int val1=Integer.parseInt(p1price.getText());
        int val2=Integer.parseInt(pqty.getText());
        int val3=val2*val1;
        ptotal.setText(val3+"");
    }//GEN-LAST:event_pqtyKeyReleased

    private void p1priceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p1priceKeyReleased
        // TODO add your handling code here:
    Pattern pa=Pattern.compile("[0-9]+");
                Matcher ma= pa.matcher(p1price.getText());
                if(!ma.matches())
                {
                    JOptionPane.showMessageDialog(null,"Please fill the valid value in price"); 
                    p1price.setText("");
                }
        int val1=Integer.parseInt(p1price.getText());
        int val2=Integer.parseInt(pqty.getText());
        int val3=val2*val1;
        ptotal.setText(val3+"");
    }//GEN-LAST:event_p1priceKeyReleased

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        Dltproduct dp= new Dltproduct();
        dp.setVisible(true);
    }//GEN-LAST:event_deleteActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        if(pitem_no.getText().trim().equals("")||prod_name.getText().trim().equals("")||jDateChooser3.getDate().equals("")||p1price.getText().trim().equals("")||pqty.getText().trim().equals("")||ptotal.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Fill the values");
        }
        else
        {
            Connection con=DbConnection.connect();
            PreparedStatement ps =null;
           // ResultSet rs=null;
            try
            {
                String sql="insert into  purchase (Product_Id,Product_Name,Date,Quantity,PerPrice,totalprice)values (?,?,?,?,?,?)";
                ps= con.prepareStatement(sql);
                ps.setString(1, pitem_no.getText());
                ps.setString(2, prod_name.getText());
                SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
                String datetime = sdf.format(jDateChooser3.getDate());
                ps.setString(3, datetime); 
          
                 
                
                  ps.setInt(4, Integer.parseInt(pqty.getText()));
                ps.setInt(5, Integer.parseInt(p1price.getText()));
                ps.setInt(6,Integer.parseInt(ptotal.getText()));
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Prduct Add Successful");
                pitem_no.setText("");
                prod_name.setText("");
                jDateChooser3.setDate(null);
                pqty.setText("");
                p1price.setText("");
                ptotal.setText("");
              
            } catch (Exception e)
            {
              JOptionPane.showMessageDialog(null,"Type the valid values");
            }finally{
                try{
                  ps.close();
               //   rs.close();
                con.close();}catch(Exception ex){
                 JOptionPane.showMessageDialog(null,ex);
                }
            }

        }
    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        Update  n= new  Update();
        n.setVisible(true);
    }//GEN-LAST:event_updateActionPerformed

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
          // TODO add your handling code here:
        this.dispose();
        Login l=new Login();
        l.setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
          setColor(Homemenu);
        resetColor(Productmenu);
        resetColor(IcecreamMenu);
        resetColor(Ordermenu);
        resetColor(Customermenu);
        resetColor(Feedbackmenu);
        Homepage.setVisible(true);
        AddPoduct.setVisible(false);
        Order.setVisible(false);
        CustomerInfo.setVisible(false);
        feedbackinfo.setVisible(false);
        IcecreamInfo.setVisible(false);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
         setColor(Productmenu);
        resetColor(Homemenu);
        resetColor(IcecreamMenu);
        resetColor(Ordermenu);
        resetColor(Customermenu);
        resetColor(Feedbackmenu);
        AddPoduct.setVisible(true);
        Order.setVisible(false);
        CustomerInfo.setVisible(false);
        feedbackinfo.setVisible(false);
        IcecreamInfo.setVisible(false);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
          setColor(IcecreamMenu);
        resetColor(Homemenu);
        resetColor(Productmenu);
        resetColor(Ordermenu);
        resetColor(Customermenu);
        resetColor(Feedbackmenu);
        IcecreamInfo.setVisible(true);
        
        try{
              Class.forName("org.sqlite.JDBC");  
            Connection con=DriverManager.getConnection("jdbc:sqlite:IcecreamParlour.sqlite");
            String sql="select Product_Id,Product_Name,Quantity,PerPrice from purchase";
            PreparedStatement ps=con.prepareStatement(sql);

            ResultSet rs=ps.executeQuery();
            viewproduct.setModel(DbUtils.resultSetToTableModel(rs));
            ps.close();
            con.close();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);

        }
        feedbackinfo.setVisible(false);
        AddPoduct.setVisible(false);
        Order.setVisible(false);
        CustomerInfo.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
          setColor(Ordermenu);
        resetColor(Homemenu);
        resetColor(IcecreamMenu);
        resetColor(Productmenu);
        resetColor(Customermenu);
        resetColor(Feedbackmenu);
        Connection con=DbConnection.connect();
        PreparedStatement ps =null;
        ResultSet rs=null;
        try{
            String sql="select * from customer_order";
            ps=con.prepareStatement(sql);
            rs=ps.executeQuery();
            order.setModel(DbUtils.resultSetToTableModel(rs));
            }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex);
        }finally{
            try{
                ps.close();
                rs.close();
                con.close();
            }catch(Exception ex){
         JOptionPane.showMessageDialog(null,ex);
        }   
        }
        Order.setVisible(true);
        AddPoduct.setVisible(false);
        IcecreamInfo.setVisible(false);
        CustomerInfo.setVisible(false);
        feedbackinfo.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        setColor(Customermenu);
        resetColor(IcecreamMenu);
        resetColor(Ordermenu);
        resetColor(Productmenu);
        resetColor(Homemenu);
        resetColor(Feedbackmenu);
        Connection con=DbConnection.connect();
        PreparedStatement ps =null;
        ResultSet rs=null;
        try {
        String sql="select * from customeraccount";
             ps=con.prepareStatement(sql);
            rs=ps.executeQuery();
            customer.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }finally{
            try{
           ps.close();
            con.close();
            rs.close();
            }catch(Exception ex){  JOptionPane.showMessageDialog(null,ex);}
                  }
        CustomerInfo.setVisible(true);
        feedbackinfo.setVisible(false);
        AddPoduct.setVisible(false);
        Order.setVisible(false);
        IcecreamInfo.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
         setColor(Feedbackmenu);
        resetColor(Homemenu);
        resetColor(IcecreamMenu);
        resetColor(Ordermenu);
        resetColor(Customermenu);
        resetColor(Productmenu);
         Connection con=DbConnection.connect();
        PreparedStatement ps =null;
        ResultSet rs=null;
        try
        {
              
            String sql="select * from feedback";
             ps=con.prepareStatement(sql);
             rs=ps.executeQuery();
            feedback.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex);
        }finally{
            try{
                ps.close();
                rs.close();
            con.close();
            }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex);
            }
        }
        feedbackinfo.setVisible(true);
        IcecreamInfo.setVisible(false);
        AddPoduct.setVisible(false);
        Order.setVisible(false);
        CustomerInfo.setVisible(false);
    }//GEN-LAST:event_jLabel12MouseClicked
void setColor(JPanel panel)
{
    panel.setBackground(new Color(255,0,0));
}
void resetColor(JPanel panel)
{
     panel.setBackground(new Color(51,51,51));
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminpanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel AddPoduct;
    private javax.swing.JPanel CustomerInfo;
    private javax.swing.JPanel Customermenu;
    private javax.swing.JPanel Feedbackmenu;
    private javax.swing.JPanel Homemenu;
    private javax.swing.JPanel Homepage;
    private javax.swing.JPanel IcecreamInfo;
    private javax.swing.JPanel IcecreamMenu;
    private javax.swing.JPanel Order;
    private javax.swing.JPanel Ordermenu;
    private javax.swing.JPanel Productmenu;
    private javax.swing.JButton add;
    private javax.swing.JTable customer;
    private javax.swing.JButton delete;
    private javax.swing.JButton dltorder;
    private javax.swing.JTable feedback;
    private javax.swing.JPanel feedbackinfo;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel logout;
    private javax.swing.JTable order;
    private javax.swing.JTextField p1price;
    private javax.swing.JTextField pitem_no;
    private javax.swing.JTextField pqty;
    private javax.swing.JTextField prod_name;
    private javax.swing.JTextField ptotal;
    private javax.swing.JButton update;
    private javax.swing.JTable viewproduct;
    // End of variables declaration//GEN-END:variables
 private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
