
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NCC
 */
public class Bill extends javax.swing.JFrame {

    /**
     * Creates new form Bill
     */
    public Bill() {
        
        initComponents();
        setIcon();
        b1.setBackground(new Color(0,0,0,64));
        b2.setBackground(new Color(0,0,0,64));
        b3.setBackground(new Color(0,0,0,64));
        b4.setBackground(new Color(0,0,0,64));
        b5.setBackground(new Color(0,0,0,64));
        b6.setBackground(new Color(0,0,0,64));
        b7.setBackground(new Color(0,0,0,64));
        b8.setBackground(new Color(0,0,0,64));
        order_no.setBackground(new Color(0,0,0,64));
     //   random();
         setDefaultCloseOperation(Bill.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        b1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        b4 = new javax.swing.JTextField();
        b6 = new javax.swing.JTextField();
        b5 = new javax.swing.JTextField();
        b7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        b8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        order_no = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(855, 580));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ice-Cream Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 68, 151, 34);

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Phone No");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 227, 151, 34);

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Product ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 174, 151, 34);

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantity");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 379, 151, 34);

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 326, 151, 34);

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total Price");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 436, 151, 34);

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 280, 151, 34);

        b1.setEditable(false);
        b1.setForeground(new java.awt.Color(255, 255, 255));
        b1.setBorder(null);
        getContentPane().add(b1);
        b1.setBounds(333, 122, 177, 34);

        b2.setEditable(false);
        b2.setForeground(new java.awt.Color(255, 255, 255));
        b2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(b2);
        b2.setBounds(333, 175, 177, 34);

        b3.setEditable(false);
        b3.setForeground(new java.awt.Color(255, 255, 255));
        b3.setBorder(null);
        getContentPane().add(b3);
        b3.setBounds(333, 380, 177, 34);

        b4.setEditable(false);
        b4.setForeground(new java.awt.Color(255, 255, 255));
        b4.setBorder(null);
        getContentPane().add(b4);
        b4.setBounds(333, 228, 177, 34);

        b6.setEditable(false);
        b6.setForeground(new java.awt.Color(255, 255, 255));
        b6.setBorder(null);
        getContentPane().add(b6);
        b6.setBounds(333, 327, 177, 34);

        b5.setEditable(false);
        b5.setForeground(new java.awt.Color(255, 255, 255));
        b5.setBorder(null);
        getContentPane().add(b5);
        b5.setBounds(333, 281, 177, 34);

        b7.setEditable(false);
        b7.setForeground(new java.awt.Color(255, 255, 255));
        b7.setBorder(null);
        getContentPane().add(b7);
        b7.setBounds(333, 437, 177, 34);

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Customer ID");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 121, 151, 34);

        b8.setEditable(false);
        b8.setForeground(new java.awt.Color(255, 255, 255));
        b8.setBorder(null);
        getContentPane().add(b8);
        b8.setBounds(333, 69, 177, 34);

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ORDER RECEIPT");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 11, 201, 39);

        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Order No");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 490, 70, 30);

        order_no.setForeground(new java.awt.Color(255, 255, 255));
        order_no.setBorder(null);
        getContentPane().add(order_no);
        order_no.setBounds(330, 490, 180, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art-artificial-background-1061581.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 870, 550);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        b1.setText(Customerpanel1.cusid.getText());
        b2.setText(Customerpanel1.prod_id.getText());
        b3.setText(Customerpanel1.qty.getText());   
        b4.setText(Customerpanel1.phn_no.getText());  
        b5.setText(Customerpanel1.date1.getText());
        b6.setText(Customerpanel1.address.getText());
        order_no.setText(Customerpanel1.orderno.getText());
        bill();
        updatetotalprice();    
   
    }//GEN-LAST:event_formWindowOpened

 public void updatetotalprice(){
     DbConnection.ddispose();
    Connection con=DbConnection.connect();
    PreparedStatement ps =null;
    ResultSet rs=null;
try{
    String sql="select PerPrice,totalprice from purchase where Product_Id="+b2.getText();
    ps=con.prepareStatement(sql);
    rs=ps.executeQuery();
    while(rs.next()){
    int k=rs.getInt("PerPrice");
    int v=rs.getInt("totalprice");
    int l=Integer.parseInt(b3.getText());
    int j=k*l;
    total(j,v);    }
    }catch(Exception ex){
    JOptionPane.showMessageDialog(null,ex);
}finally{
    try{
        ps.close();
        rs.close();
        con.close();}
    
    catch(SQLException ex){
      JOptionPane.showMessageDialog(null,ex);
    }
}
}
void total(int a,int b){
    DbConnection.ddispose();
    Connection con=DbConnection.connect();
    PreparedStatement ps =null;
   
        try{
            String val = '"' +b2.getText()+ '"';
            String sqql="update purchase set totalprice=?  where Product_Id="+val;
            ps=con.prepareStatement(sqql);
            int z=b-a;
            ps.setInt(1,z);
            ps.executeUpdate();
            }
        catch(Exception ex) {
                JOptionPane.showMessageDialog(null,ex);
            }finally{
            try{
                 ps.close();
                con.close();}
            catch(SQLException ex){
             JOptionPane.showMessageDialog(null,ex);
            }
        }
}
void bill(){

    Connection con=DbConnection.connect();
   PreparedStatement ps =null;
    ResultSet rs=null;
    try{
         String val = '"' +b2.getText()+ '"';
        String sql="select Product_Name,PerPrice from purchase where Product_Id="+val;
        ps=con.prepareStatement(sql);
        rs=ps.executeQuery();
        if(rs.next())
        {
        String add1=rs.getString("Product_Name");
        b8.setText(add1);
        int add2=rs.getInt("PerPrice");
        int f=Integer.parseInt(b3.getText());
        int a=add2*f;
        b7.setText(a+"");
        }   
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"bill function");
        }finally{
        try{
        ps.close();
        rs.close();
        con.close();}
        catch(SQLException ex){ }
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Bill().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JTextField b5;
    private javax.swing.JTextField b6;
    public static javax.swing.JTextField b7;
    private javax.swing.JTextField b8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField order_no;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
