
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NCC
 */
public class CreateAccount extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public CreateAccount() {
        initComponents();
       setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cid = new javax.swing.JTextField();
        cname = new javax.swing.JTextField();
        psswd = new javax.swing.JTextField();
        phn = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        date3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(850, 580));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 177, 111, 27);

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer Id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 81, 111, 27);

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 129, 111, 27);

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 222, 111, 27);

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone no");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 277, 111, 27);

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 323, 111, 27);

        cid.setEditable(false);
        getContentPane().add(cid);
        cid.setBounds(236, 78, 170, 30);
        getContentPane().add(cname);
        cname.setBounds(236, 126, 170, 30);
        getContentPane().add(psswd);
        psswd.setBounds(236, 174, 170, 30);
        getContentPane().add(phn);
        phn.setBounds(236, 278, 166, 27);

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(236, 323, 166, 71);

        jButton2.setBackground(new java.awt.Color(102, 204, 0));
        jButton2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(231, 421, 170, 36);

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Create Account");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 30, 208, 32);

        date3.setEditable(false);
        getContentPane().add(date3);
        date3.setBounds(240, 230, 160, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art-artificial-background-1061581.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-6, 0, 890, 550);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        try { 
                Class.forName("org.sqlite.JDBC");  
            Connection con=DriverManager.getConnection("jdbc:sqlite:IcecreamParlour.sqlite");
                String sql="insert into  customeraccount(Id,Name,Password,Date,Phnno,Address) values (?,?,?,?,?,?)";
                PreparedStatement ps= con.prepareStatement(sql);
             //   ps.setInt(1, Integer.parseInt(cid.getText()));
                     ps.setString(1,cid.getText());  
             ps.setString(2, cname.getText());
                ps.setString(3, psswd.getText());
                //SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
                //String datetime = sdf.format(jDateChooser1.getDate());
                 String Date = date3.getText();
                ps.setString(4, Date);
                Pattern p=Pattern.compile("^(\\+91[\\-\\s]?)?[0]?(91)?[789]\\d{9}$");
                Matcher m= p.matcher(phn.getText());
                if(!m.matches())
                {
                    JOptionPane.showMessageDialog(null,"Invalid Phone no"); 
                }
                else
                {   
                    ps.setDouble(5,Double.parseDouble(phn.getText()));
                }
                ps.setString(6,address.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Account is Create");
                ps.close();
                con.close();
                this.dispose();
                
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Type the valid values");
        }     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
           try{
           Class.forName("org.sqlite.JDBC");  
            Connection con=DriverManager.getConnection("jdbc:sqlite:IcecreamParlour.sqlite");
                String qry="Select Id from customeraccount order by Id desc limit 1";
            
                PreparedStatement ps= con.prepareStatement(qry);
       ResultSet rs=ps.executeQuery();
        if(rs.next()){
        String rl=rs.getString("Id");
        int ln=rl.length();
        String stxt=rl.substring(0,2);
        String snum=rl.substring(2,ln);
        int n=Integer.parseInt(snum);
        n++;
        snum=Integer.toString(n);
        String v=stxt+snum;
        cid.setText(v);
        }
        else{cid.setText("IC101");}
        ps.close();
        rs.close();
        con.close();
           }catch(Exception ex){ }
             Date d=new Date();
                
                SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
            date3.setText(sdf.format(d));
    }//GEN-LAST:event_formWindowOpened
 
                      
              
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JTextField cid;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField date3;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField phn;
    private javax.swing.JTextField psswd;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
