
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NCC
 */
public class DltOrder extends javax.swing.JFrame {

    /**
     * Creates new form dltsales
     */
    public DltOrder() {
        initComponents();
        setDefaultCloseOperation(DltOrder.DISPOSE_ON_CLOSE);
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        searchfordlt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        prod_id = new javax.swing.JTextField();
        dqty = new javax.swing.JTextField();
        dltdate = new com.toedter.calendar.JDateChooser();
        phnno = new javax.swing.JTextField();
        dltorder = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cus_id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(855, 580));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search by Order No");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 70, 150, 30);

        searchfordlt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchfordltKeyPressed(evt);
            }
        });
        getContentPane().add(searchfordlt);
        searchfordlt.setBounds(310, 70, 170, 29);

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 170, 111, 21);

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 120, 111, 30);

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantity");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 220, 111, 21);

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone No");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 270, 111, 21);

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 320, 60, 21);

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Address");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 410, 111, 21);

        prod_id.setEditable(false);
        getContentPane().add(prod_id);
        prod_id.setBounds(310, 170, 170, 30);

        dqty.setEditable(false);
        getContentPane().add(dqty);
        dqty.setBounds(310, 220, 170, 30);
        getContentPane().add(dltdate);
        dltdate.setBounds(310, 320, 170, 27);

        phnno.setEditable(false);
        getContentPane().add(phnno);
        phnno.setBounds(310, 270, 170, 30);

        dltorder.setBackground(new java.awt.Color(204, 0, 0));
        dltorder.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 15)); // NOI18N
        dltorder.setForeground(new java.awt.Color(255, 255, 255));
        dltorder.setText("DELETE");
        dltorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltorderActionPerformed(evt);
            }
        });
        getContentPane().add(dltorder);
        dltorder.setBounds(80, 480, 150, 40);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(504, 71, 0, 0);

        cus_id.setEditable(false);
        getContentPane().add(cus_id);
        cus_id.setBounds(310, 120, 170, 30);

        address.setEditable(false);
        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(310, 380, 166, 90);

        jLabel12.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DELETE ORDER");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(100, 10, 280, 30);

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Type  Order_No  which  u  want  to  delete  and  press  Enter");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(520, 70, 320, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art-artificial-background-1061581.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-6, 0, 930, 550);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dltorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltorderActionPerformed
        // TODO add your handling code here:
        if(searchfordlt.getText().trim().equals("")||cus_id.getText().trim().equals("")||prod_id.getText().trim().equals("")||dltdate.getDate().equals("")||dqty.getText().trim().equals("")||phnno.getText().trim().equals("")||address.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(this,"fill the values");
        }
        else{
            Connection con=DbConnection.connect();
            PreparedStatement ps=null;
            ResultSet rs=null;
            String val = '"' + searchfordlt.getText()+ '"';
            try{
                    String sql= "delete from customer_order where Orderno="+val;
        //    String sql= "delete from customer_order where Orderno="+searchfordlt.getText();
            System.out.println(sql);
            ps=con.prepareStatement(sql);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Deleted Order");
            searchfordlt.setText("");
            cus_id.setText("");
            prod_id.setText("");
            dltdate.setDate(null);
            dqty.setText("");
            phnno.setText("");
            address.setText("");
        }catch( Exception ex){
           JOptionPane.showMessageDialog(null,"ff");
        }finally{
                try{
                ps.close();
                rs.close();
                con.close();
                }catch(Exception ex){ 
                    //JOptionPane.showMessageDialog(null,ex);
                }
            }
                }    
    }//GEN-LAST:event_dltorderActionPerformed

    private void searchfordltKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchfordltKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){ 
       Connection con= DbConnection.connect();
        PreparedStatement  ps=null;
        ResultSet rs=null;
       try
        {
            String sql="select * from customer_order where Orderno=?";
            ps=con.prepareStatement(sql);
//            ps.setInt(1,Integer.parseInt(searchfordlt.getText()));
            ps.setString(1,searchfordlt.getText());
            rs=ps.executeQuery();
           if(rs.next()){
                String add1=rs.getString("cus_id");
                cus_id.setText(add1);
                String add2=rs.getString("Prod_id"); 
                prod_id.setText(add2);
                String add3=rs.getString("Qnty");
                dqty.setText(add3);
                String add4=rs.getString("phnno");
                phnno.setText(add4);
                String add5 = rs.getString("Date");
               java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(add5);
                dltdate.setDate(date);
                String add6=rs.getString("address");
                address.setText(add6);
            }else{JOptionPane.showMessageDialog(null,"Order_No is Wrong");}
                }
        catch(Exception ex){JOptionPane.showMessageDialog(null,ex);        }
        finally{
           try{
            ps.close();
            rs.close();
            con.close();
           }catch(Exception ex){JOptionPane.showMessageDialog(null,ex);}
       }
        }
     

    }//GEN-LAST:event_searchfordltKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DltOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DltOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DltOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DltOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DltOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JTextField cus_id;
    private com.toedter.calendar.JDateChooser dltdate;
    private javax.swing.JButton dltorder;
    private javax.swing.JTextField dqty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField phnno;
    private javax.swing.JTextField prod_id;
    private javax.swing.JTextField searchfordlt;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
