
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NCC
 */
public class Dltproduct extends javax.swing.JFrame {

    /**
     * Creates new form dltpurchase
     */
    public Dltproduct() {
        initComponents();
        setDefaultCloseOperation(Dltproduct.DISPOSE_ON_CLOSE);
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        search1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ditem_no = new javax.swing.JTextField();
        d1price = new javax.swing.JTextField();
        dqty = new javax.swing.JTextField();
        dtotal = new javax.swing.JTextField();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        delete = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        prod_name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(855, 580));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search By Product ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 70, 150, 40);

        search1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                search1KeyPressed(evt);
            }
        });
        getContentPane().add(search1);
        search1.setBounds(270, 80, 180, 30);

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 130, 121, 23);

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 250, 121, 23);

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Product Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 190, 121, 23);

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Quantity");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 310, 121, 23);

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("One Item Price");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 370, 121, 23);

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total Price");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 430, 121, 23);

        ditem_no.setEditable(false);
        getContentPane().add(ditem_no);
        ditem_no.setBounds(270, 130, 180, 29);

        d1price.setEditable(false);
        getContentPane().add(d1price);
        d1price.setBounds(270, 370, 180, 29);

        dqty.setEditable(false);
        getContentPane().add(dqty);
        dqty.setBounds(270, 310, 180, 29);

        dtotal.setEditable(false);
        getContentPane().add(dtotal);
        dtotal.setBounds(270, 430, 180, 29);
        getContentPane().add(jDateChooser4);
        jDateChooser4.setBounds(270, 250, 180, 31);

        delete.setBackground(new java.awt.Color(204, 0, 0));
        delete.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 15)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(60, 480, 120, 40);

        jLabel12.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DELETE PRODUCT");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(60, 20, 280, 40);

        prod_name.setEditable(false);
        getContentPane().add(prod_name);
        prod_name.setBounds(270, 190, 180, 30);

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Type  Product_Id  which  u  want  to  delete  and  press  Enter");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(500, 80, 330, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art-artificial-background-1061581.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-6, 0, 870, 550);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
  
        if(search1.getText().trim().equals("")||ditem_no.getText().trim().equals("")||prod_name.getText().trim().equals("")||jDateChooser4.getDate().equals("")||d1price.getText().trim().equals("")||dqty.getText().trim().equals("")||dtotal.getText().trim().equals(""))
       { 
             JOptionPane.showMessageDialog(this,"fill the values");
       }
       else
       {
        Connection con=DbConnection.connect();
        PreparedStatement ps =null;
        ResultSet rs=null;
             try
                {
                    String sql= "delete from purchase where Product_Id="+search1.getText();
                    ps=con.prepareStatement(sql);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Deleted Product");
                    search1.setText("");
                    ditem_no.setText("");
                    prod_name.setText("");
                    jDateChooser4.setDate(null);
                    d1price.setText("");
                    dqty.setText("");
                     dtotal.setText("");
                }catch( Exception ex)
                {
                     JOptionPane.showMessageDialog(null,ex);
                }finally{
        try{
        ps.close();
        rs.close();
        con.close();}
        catch(SQLException ex){JOptionPane.showMessageDialog(null,ex); }
    }
       }
    }//GEN-LAST:event_deleteActionPerformed

    private void search1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){ 
             Connection con=DbConnection.connect();
        PreparedStatement ps =null;
        ResultSet rs=null;
         try{
            String sql="select * from purchase where Product_Id=?";
            ps=con.prepareStatement(sql);
            ps.setInt(1,Integer.parseInt(search1.getText()));
            rs=ps.executeQuery();
            if(rs.next())
            {
                String add1=rs.getString("Product_Id");
                ditem_no.setText(add1);
                String add2=rs.getString("Product_Name"); 
                prod_name.setText(add2);
               
                String add3 = rs.getString("Date");
               java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(add3);
                jDateChooser4.setDate(date);
                String add4=rs.getString("Quantity");
                dqty.setText(add4);
                String add5=rs.getString("PerPrice");
                d1price.setText(add5);
                String add6=rs.getString("totalprice");
                dtotal.setText(add6);
            }else{JOptionPane.showMessageDialog(null,"Product-ID is Wrong");}
            }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }finally{
        try{
        ps.close();
        rs.close();
        con.close();}
        catch(SQLException ex){JOptionPane.showMessageDialog(null,ex); }
    }
        }
       
    }//GEN-LAST:event_search1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dltproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dltproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dltproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dltproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dltproduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField d1price;
    private javax.swing.JButton delete;
    private javax.swing.JTextField ditem_no;
    private javax.swing.JTextField dqty;
    private javax.swing.JTextField dtotal;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField prod_name;
    private javax.swing.JTextField search1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
