
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NCC
 */
public class Update extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame2
     */
    public Update() {
        initComponents();
        setIcon();
        setDefaultCloseOperation(Update.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        uitem_no = new javax.swing.JTextField();
        u1price = new javax.swing.JTextField();
        utotal = new javax.swing.JTextField();
        uqty = new javax.swing.JTextField();
        jDateChooser5 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        uprod_name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(855, 580));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Product Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 210, 111, 23);

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 160, 130, 23);

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 270, 111, 23);

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("One Item Price");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 390, 97, 23);

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Quantity");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 330, 111, 23);

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total Price");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 450, 111, 23);
        getContentPane().add(uitem_no);
        uitem_no.setBounds(290, 150, 170, 28);

        u1price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                u1priceKeyReleased(evt);
            }
        });
        getContentPane().add(u1price);
        u1price.setBounds(290, 390, 170, 28);
        getContentPane().add(utotal);
        utotal.setBounds(290, 450, 170, 28);

        uqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                uqtyKeyReleased(evt);
            }
        });
        getContentPane().add(uqty);
        uqty.setBounds(290, 330, 170, 28);
        getContentPane().add(jDateChooser5);
        jDateChooser5.setBounds(290, 270, 170, 27);

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("UPDATE");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(560, 150, 130, 40);

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(290, 90, 170, 30);

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Search By Product ID");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 80, 150, 50);

        jLabel12.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("UPDATE PRODUCT");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(80, 20, 280, 40);
        getContentPane().add(uprod_name);
        uprod_name.setBounds(290, 210, 170, 30);

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Type  Product_Id  which  u  want  to  Update  and  press  Enter");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(500, 90, 330, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art-artificial-background-1061581.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 870, 550);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       if(search.getText().trim().equals("")||uitem_no.getText().trim().equals("")||uprod_name.getText().trim().equals("")||jDateChooser5.getDate().equals("")||u1price.getText().trim().equals("")||uqty.getText().trim().equals("")||utotal.getText().trim().equals(""))
       { 
        JOptionPane.showMessageDialog(this,"fill the values");
        }
        else{
        Connection con=DbConnection.connect();
        PreparedStatement ps =null;
        ResultSet rs=null;
                try{
                        String sql= "update purchase set Product_Id=?, Product_Name=?,Date=?,Quantity=?,PerPrice=?,totalprice=? where Product_Id=0"+search.getText();
                        ps=con.prepareStatement(sql);
                        ps.setInt(1, Integer.parseInt(uitem_no.getText()));
                        ps.setString(2, uprod_name.getText());
                        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
                        String datetime = sdf.format(jDateChooser5.getDate());
                        ps.setString(3, datetime);
                        ps.setInt(4,Integer.parseInt(uqty.getText()));
                        ps.setInt(5,Integer.parseInt(u1price.getText()));
                        ps.setInt(6,Integer.parseInt(utotal.getText()));
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(null,"Update Product");
                        ps.close();
                         con.close();
                        dispose();
                    }catch(Exception ex)
                    {
                        JOptionPane.showMessageDialog(null,"put the valid values");
                    }finally{
                            try{
                            ps.close();
                            rs.close();
                            con.close();}
                            catch(SQLException ex){JOptionPane.showMessageDialog(null,ex); }
                        }
                                }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void uqtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uqtyKeyReleased
        // TODO add your handling code here:
        int val1=Integer.parseInt(u1price.getText());
         int val2=Integer.parseInt(uqty.getText());
         int val3=val2*val1;
        utotal.setText(val3+"");   
    }//GEN-LAST:event_uqtyKeyReleased

    private void u1priceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_u1priceKeyReleased
        // TODO add your handling code here:
         int val1=Integer.parseInt(u1price.getText());
         int val2=Integer.parseInt(uqty.getText());
         int val3=val2*val1;
        utotal.setText(val3+""); 
    }//GEN-LAST:event_u1priceKeyReleased

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        // TODO add your handling code here:
         Connection con=DbConnection.connect();
        PreparedStatement ps =null;
        ResultSet rs=null;
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){ 
         try{
            String sql="select * from purchase where Product_Id="+search.getText();
            ps=con.prepareStatement(sql);
            rs=ps.executeQuery();
            if(rs.next()){
                     
                String add1=rs.getString("Product_Id");
                uitem_no.setText(add1);
                String add2=rs.getString("Product_Name"); 
                uprod_name.setText(add2);
                String dateValue = rs.getString("Date"); // What ever column
                java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue);
                jDateChooser5.setDate(date);
                String add4=rs.getString("Quantity");
                uqty.setText(add4);
                String add5=rs.getString("PerPrice");
                u1price.setText(add5);
                String add6=rs.getString("totalprice");
                utotal.setText(add6);
                }
                else{JOptionPane.showMessageDialog(null,"Product-ID is Wrong");}
                }
        catch(Exception ex){JOptionPane.showMessageDialog(null,ex);}
         finally{
        try{
        ps.close();
        rs.close();
        con.close();}
        catch(SQLException ex){JOptionPane.showMessageDialog(null,ex); }
    }
        }
    }//GEN-LAST:event_searchKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField search;
    private javax.swing.JTextField u1price;
    private javax.swing.JTextField uitem_no;
    private javax.swing.JTextField uprod_name;
    private javax.swing.JTextField uqty;
    private javax.swing.JTextField utotal;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
